/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // DistributeIQ Design System Tokens
        'primary':                  '#006591',
        'on-primary':               '#ffffff',
        'primary-container':        '#0ea5e9',
        'on-primary-container':     '#003751',
        'primary-fixed':            '#c9e6ff',
        'primary-fixed-dim':        '#89ceff',
        'on-primary-fixed':         '#001e2f',
        'on-primary-fixed-variant': '#004c6e',
        'inverse-primary':          '#89ceff',

        'secondary':                '#006b5f',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#6df5e1',
        'on-secondary-container':   '#006f64',
        'secondary-fixed':          '#71f8e4',
        'secondary-fixed-dim':      '#4fdbc8',
        'on-secondary-fixed':       '#00201c',
        'on-secondary-fixed-variant':'#005048',

        'tertiary':                 '#006e2f',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#00b351',
        'on-tertiary-container':    '#003c16',
        'tertiary-fixed':           '#6bff8f',
        'tertiary-fixed-dim':       '#4ae176',
        'on-tertiary-fixed':        '#002109',
        'on-tertiary-fixed-variant':'#005321',

        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',

        'surface':                  '#f6fafe',
        'surface-dim':              '#d6dade',
        'surface-bright':           '#f6fafe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f0f4f8',
        'surface-container':        '#eaeef2',
        'surface-container-high':   '#e4e9ed',
        'surface-container-highest':'#dfe3e7',
        'surface-variant':          '#dfe3e7',
        'surface-tint':             '#006591',
        'on-surface':               '#171c1f',
        'on-surface-variant':       '#3e4850',
        'inverse-surface':          '#2c3134',
        'inverse-on-surface':       '#edf1f5',

        'background':               '#f6fafe',
        'on-background':            '#171c1f',

        'outline':                  '#6e7881',
        'outline-variant':          '#bec8d2',
      },
      fontFamily: {
        'display':   ['Space Grotesk', 'sans-serif'],
        'headline':  ['Space Grotesk', 'sans-serif'],
        'body':      ['Inter', 'sans-serif'],
        'label':     ['Inter', 'sans-serif'],
        sans:        ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg':   ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':   ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':   ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg':  ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md':  ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm':  ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm':      '0.25rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':  '4px',
        'sm':  '8px',
        'md':  '16px',
        'lg':  '24px',
        'xl':  '32px',
        'xxl': '48px',
        'base':'8px',
        'gutter': '16px',
        'container-margin': '24px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.08), 0 10px 15px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.1), 0 20px 25px rgba(0,0,0,0.06)',
        'glass': '0 8px 32px rgba(0,101,145,0.08)',
      },
      backdropBlur: {
        'xs': '4px',
      },
    },
  },
  plugins: [],
}
